In [1]:
# pip install numpy matplotlib

In [2]:
import numpy as np

- create
- basic operation
- math operation
- indexing and slicing
- boolean filter

In [3]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [5]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [7]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*100)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4

In [8]:
np.random.rand(3,3)

array([[0.09023011, 0.74213986, 0.84811827],
       [0.01752986, 0.14632084, 0.76660716],
       [0.00478935, 0.37250937, 0.46154389]])

In [10]:
r1 = np.random.randint(-5,6,(5,5))
print(r1)

[[ 0 -5  1  5  0]
 [ 5  4  3  3  4]
 [-3 -4  4 -3 -3]
 [-4  5 -1 -2  5]
 [ 5  3  3 -2 -4]]


In [11]:
np.arange(0,50, .5)#start stop gap

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [13]:
np.linspace(0,50,100)#number of items

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

array attributes
- shape
- dtype
- ndim
- size

# basic operation
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [14]:
x = np.random.rand(3,3)
x.dtype

dtype('float64')

In [15]:
x.ndim

2

In [16]:
z = np.random.randint(1,5,(3,3,3))
z.ndim

3

In [17]:
z.size

27

In [18]:
z.sum()

np.int64(64)

In [21]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis = 0))#row wise
print(a.sum(axis = 1))#row wise
print(a.mean())
print(a.min())
print(a.max())


2.1609033273038496
[1.33732178 0.13153037 0.69205118]
[1.29191029 0.86899303]
0.3601505545506416
0.050872427955378274
0.7984592560088258


In [27]:
z= np.random.randint(11,99,(5,5))
print(z)
print('tanspose')
print(z.transpose())
print(z.T)
print('flattened')
print(z.flatten())

[[82 24 44 74 21]
 [66 59 44 66 77]
 [30 26 83 64 98]
 [67 65 42 31 75]
 [43 59 70 27 89]]
tanspose
[[82 66 30 67 43]
 [24 59 26 65 59]
 [44 44 83 42 70]
 [74 66 64 31 27]
 [21 77 98 75 89]]
[[82 66 30 67 43]
 [24 59 26 65 59]
 [44 44 83 42 70]
 [74 66 64 31 27]
 [21 77 98 75 89]]
flattened
[82 24 44 74 21 66 59 44 66 77 30 26 83 64 98 67 65 42 31 75 43 59 70 27
 89]


In [29]:
a = np.random.randint(1,10,(4,5))
print(a)
print(a.reshape(20))
print(a.reshape(5,4))
print(a.reshape(4,5))
print(a.reshape(2,10))
print(a.reshape(10,2))

[[1 2 6 8 9]
 [9 6 3 9 4]
 [6 7 9 7 5]
 [3 3 4 8 1]]
[1 2 6 8 9 9 6 3 9 4 6 7 9 7 5 3 3 4 8 1]
[[1 2 6 8]
 [9 9 6 3]
 [9 4 6 7]
 [9 7 5 3]
 [3 4 8 1]]
[[1 2 6 8 9]
 [9 6 3 9 4]
 [6 7 9 7 5]
 [3 3 4 8 1]]
[[1 2 6 8 9 9 6 3 9 4]
 [6 7 9 7 5 3 3 4 8 1]]
[[1 2]
 [6 8]
 [9 9]
 [6 3]
 [9 4]
 [6 7]
 [9 7]
 [5 3]
 [3 4]
 [8 1]]


In [30]:
a = np.array([[1,2],[5,7]])
b = np.array([[3,4],[5,7]])
print(a)
print(b)

[[1 2]
 [5 7]]
[[3 4]
 [5 7]]


In [31]:
print(a +b)
print(a - b)
print(a / b)
print(a @b)
print(a.dot(b))


[[ 4  6]
 [10 14]]
[[-2 -2]
 [ 0  0]]
[[0.33333333 0.5       ]
 [1.         1.        ]]
[[13 18]
 [50 69]]
[[13 18]
 [50 69]]


In [32]:
# when using matrix and scalar
print(a- 10)#broadcasting
print(a * 10)
print(a / 10)
print(a + 10)

[[-9 -8]
 [-5 -3]]
[[10 20]
 [50 70]]
[[0.1 0.2]
 [0.5 0.7]]
[[11 12]
 [15 17]]


In [33]:
#indexing 
print(a[0,0])
print(a[-1,-1])

1
7


In [36]:
# slicing 
x = np.random.randint(1,10,(5,5))
print(x)
#syntax of slicing arr[rs:rstop:rgap]
print(x[:,0])
print(x[:,-1])
print(x[:,:3])

[[3 9 9 7 9]
 [4 1 9 2 6]
 [7 6 7 4 3]
 [6 4 6 9 7]
 [2 4 3 6 8]]
[3 4 7 6 2]
[9 6 3 7 8]
[[3 9 9]
 [4 1 9]
 [7 6 7]
 [6 4 6]
 [2 4 3]]


In [40]:
print(x[1:3,1:5])

[[1 9 2 6]
 [6 7 4 3]]
