In [ ]:
#creare a string and print it
a= "My favourite movie is Harry Potter"
print(a)
print(type(a))
print(len(a))

In [ ]:
msg = "python is great"
print (msg [-5:])

In [ ]:
word = " Python is everywhere"
print (word[-1])
print (word[-2])
print (word[-3])
print (word[-4])
print (word[-5])
print (word[-6])
print (word[-7])
print (word[-8])
print (word[-9])
print (word[-10])

In [ ]:
b= "hello world"
print(b[::-1])

In [ ]:
txt= "how are you?"
print(txt.upper())
text = "How Is It Going?"
print(text.lower())

In [ ]:
p= ['python','is','easy', 'to','learn']
print(p)
full_p = "/".join(p)
print(full_p)

In [ ]:
ch = """Twinkle Twinkle,  little star,
How i wonder , what you are
Up above the world so high,
like a diamond , in the sky"""
ch.splitlines()



In [ ]:
s1="python"
s2 = "is"
s3 = "great"
result = " ".join([s1,s2,s3])
print(result)


In [ ]:
for i in range (1,10):
    print (f'{i}.')

In [ ]:
sen = input("enter any sentence")
j = sen.split()
for word in j:
    print(word)
c = sen.count('e')
print('the number of e in the sentence',c)


In [ ]:
txt = '    this is not a good string  '
print (len(txt),txt)
clear_txt = txt.strip()
print(len(clear_txt),clear_txt)


# LOOPS 

In [ ]:
#wap a program to print number from 1 to 10 using for loop
nums = 11
for i in range (1,11):
    print(i)

In [ ]:
#WAP  a program to print multiplcation table of a given number using a while loop
num = int(input("enter the number"))
i = 1
while i <= 10:
    product = num*i
    print(f"{num} * {i} = {product}")

In [ ]:
#wap a program to print a sum of all even number between 1 to 100
sum = 0 
for i in range (1,10):
    if i % 2 == 0:
        continue
    sum += i
    print(sum)

In [ ]:
#prime number
num = int(input("enter the number"))
if num > 1:
    for i  in range (2,(num//2)+1):
        if num % i==0:
            print (f"{num} is not the prime number")
            break
    else:
        print(f"{num} is the prime number ")
else:
    print(f"{num }is not a prime number")


In [1]:
import numpy as np

In [ ]:
a =np.array([0]*10)
print (a)
b = np.array([1]*10)
print(b)

In [ ]:
z = np.random.randint(0,8,(3,3))
print(z)

In [16]:
z= np.array([0,1,2,3,4,5,6,7,8,9])
nz = z[::-1]
print(nz)

[9 8 7 6 5 4 3 2 1 0]


In [20]:
c = ([0,1,2,3,4,5,6,7,8,9])
print(f"array = {c}")
nc = np.flip(c)
print(f"reversed array = {nc}")

array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
reversed array = [9 8 7 6 5 4 3 2 1 0]


In [23]:
m = np.array([[1,2,3],[4,5,6]])
nm = np.flip(m)
print(f"reversed array= {nm}")

reversed array= [[6 5 4]
 [3 2 1]]


In [9]:
num = np.array([[23,56,9],[87,12,24],[67,90,56]])
even_mask = num %2 == 0
even_num = num[even_mask]
print('even numbers : ',even_num)



even numbers :  [56 12 24 90 56]


In [6]:
num = np.array([12,23,3,445,55,66,78,9,80])
print(num.sum())

771


In [11]:
n= np.array([[12,34,56],[76,98,76]])
print(n.sum())
print(n.sum(axis = 0))
print(n.sum(axis = 1))
print(n.mean())
print(n.std())

352
[ 88 132 132]
[102 250]
58.666666666666664
28.697657666707844


In [22]:
a = np.random.randint(0,99,(5,5))
print(a)
print(f'minimum value = {a.min()}')
print(f'maximum value = {a.max()}')

[[98 74 68 23 12]
 [ 0 78 81 42 11]
 [58 19 53 19 30]
 [ 5  2 71 72 30]
 [37 41 15 49 29]]
minimum value = 0
maximum value = 98


In [10]:
x = np.ones((5,5))
c = x[1:-1,1:-1] =0
print('original array')
print(x)

#c =x[1:-1,1:-1] = 0
print('\n 1 on the border and 0 inside')
print(c)


original array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

 1 on the border and 0 inside
0


In [41]:
x = np.array([[10,20,30],[40,50,60]])
print(x[1,2])
print(x)
#print(x.size())

60
[[10 20 30]
 [40 50 60]]


In [47]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
subarr = arr1[0:2]
print(subarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[3,4,1],[6,7,8],[2,3,5]])
result = np.dot(a,b)
print("matrix a")
print(a)
print("Matrix b")
print(b)
print("Matrix Multiplication of a and b")
print(result)

matrix a
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix b
[[3 4 1]
 [6 7 8]
 [2 3 5]]
Matrix Multiplication of a and b
[[ 21  27  32]
 [ 54  69  74]
 [ 87 111 116]]


In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
import plotly.express as px